// Generated by CoffeeScript 1.3.3
var frontToBack, handleOrientationEvent, leftToRight, print, rotateDegrees;

if (window.DeviceOrientationEvent) {
  window.addEventListener("deviceorientation", (function(event) {
    var frontToBack, leftToRight, rotateDegrees;
    rotateDegrees = event.alpha;
    leftToRight = event.gamma;
    frontToBack = event.beta;
    return handleOrientationEvent(frontToBack, leftToRight, rotateDegrees);
  }), false);
}

frontToBack = 0;

leftToRight = 0;

rotateDegrees = 0;

print = _.throttle(function() {
  return $('#text').text("" + frontToBack + " " + leftToRight + " " + rotateDegrees);
}, 2000);

handleOrientationEvent = function(_frontToBack, _leftToRight, _rotateDegrees) {
  frontToBack = _frontToBack;
  leftToRight = _leftToRight;
  rotateDegrees = _rotateDegrees;
  return print();
};
